"""
Download favicons for popular domains and generate a C header with embedded byte arrays.
Usage: python gen_favicons.py
Output: favicon_data.h
"""
import urllib.request
import os
import sys

DOMAINS = [
    "google.com", "youtube.com", "facebook.com", "amazon.com", "apple.com",
    "microsoft.com", "x.com", "instagram.com", "linkedin.com", "reddit.com",
    "netflix.com", "github.com", "stackoverflow.com", "wikipedia.org", "yahoo.com",
    "twitch.tv", "discord.com", "spotify.com", "pinterest.com", "paypal.com",
    "ebay.com", "walmart.com", "target.com", "bestbuy.com", "dropbox.com",
    "adobe.com", "zoom.us", "slack.com", "notion.so", "figma.com",
    "cloudflare.com", "godaddy.com", "namecheap.com", "digitalocean.com",
    "stripe.com", "shopify.com", "wordpress.com", "medium.com", "tumblr.com",
    "tiktok.com", "snapchat.com", "whatsapp.com", "telegram.org", "signal.org",
    "proton.me", "icloud.com", "outlook.com", "steampowered.com", "roblox.com",
    "epicgames.com",
]

API_URL = "https://www.google.com/s2/favicons?domain={}&sz=32"

def sanitize_name(domain):
    """google.com -> google_com"""
    return domain.replace(".", "_").replace("-", "_")

def bytes_to_c_array(data):
    """Convert bytes to C hex array string."""
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    return "\n".join(lines)

def main():
    # Create temp dir for downloads
    tmp_dir = os.path.join(os.path.dirname(__file__), "_favicon_tmp")
    os.makedirs(tmp_dir, exist_ok=True)

    entries = []  # (domain, sanitized_name, byte_data)

    for domain in DOMAINS:
        cache_path = os.path.join(tmp_dir, f"{domain}.png")

        # Use cached file if exists
        if os.path.exists(cache_path) and os.path.getsize(cache_path) > 100:
            with open(cache_path, "rb") as f:
                data = f.read()
            print(f"  [cached] {domain} ({len(data)} bytes)")
            entries.append((domain, sanitize_name(domain), data))
            continue

        url = API_URL.format(domain)
        print(f"  Fetching {domain}...", end=" ", flush=True)
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = resp.read()

            if len(data) < 100:
                print(f"SKIP (too small: {len(data)} bytes)")
                continue

            with open(cache_path, "wb") as f:
                f.write(data)
            print(f"OK ({len(data)} bytes)")
            entries.append((domain, sanitize_name(domain), data))
        except Exception as e:
            print(f"FAIL ({e})")

    # Generate header
    out_path = os.path.join(os.path.dirname(__file__), "favicon_data.h")
    with open(out_path, "w") as f:
        f.write("// Auto-generated by gen_favicons.py — do not edit\n")
        f.write("#pragma once\n\n")

        # Byte arrays
        for domain, name, data in entries:
            f.write(f"// {domain} ({len(data)} bytes)\n")
            f.write(f"static const unsigned char s_fav_{name}[] = {{\n")
            f.write(bytes_to_c_array(data))
            f.write("\n};\n\n")

        # Lookup table
        f.write("struct BundledFavicon {\n")
        f.write("    const char* domain;\n")
        f.write("    const unsigned char* data;\n")
        f.write("    unsigned int size;\n")
        f.write("};\n\n")
        f.write(f"static const BundledFavicon s_bundled_favicons[] = {{\n")
        for domain, name, data in entries:
            f.write(f'    {{ "{domain}", s_fav_{name}, {len(data)} }},\n')
        f.write("};\n\n")
        f.write(f"static const int s_bundled_favicon_count = {len(entries)};\n")

    print(f"\nGenerated {out_path} with {len(entries)} icons")

if __name__ == "__main__":
    main()
